DROP TABLE IF EXISTS `cartProducts`;
DROP TABLE IF EXISTS `wishlistProducts`;
DROP TABLE IF EXISTS `carts`;
DROP TABLE IF EXISTS `wishlists`;
DROP TABLE IF EXISTS `orderProducts`;
DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `addresses`;
DROP TABLE IF EXISTS `products`;
DROP TABLE IF EXISTS `productTypes`;
DROP TABLE IF EXISTS `brands`;


