CREATE TABLE IF NOT EXISTS orders 
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    userId INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status INT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT FK_orders_users
    FOREIGN KEY (userId)
    REFERENCES users(id)
    ON DELETE CASCADE
) ENGINE=INNODB;