CREATE TABLE IF NOT EXISTS watches
(
    id INT UNSIGNED PRIMARY KEY NOT NULL,
    name VARCHAR(30) NOT NULL,
    price INT UNSIGNED NOT NULL,
    image VARCHAR(100) NOT NULL,
    colour1 VARCHAR(50) NOT NULL,
    colour2 VARCHAR(50) NOT NULL,
    brandId INT UNSIGNED NOT NULL,
    CONSTRAINT FK_watches_brands
        FOREIGN KEY (brandId)
        REFERENCES brands(id)
) ENGINE=INNODB;
